# this file is linked via wallust.nix file and will recreate the wallust.toml from ressources
# REBUILD MUST BE RUN TO UPDATE THE SYMLINK

# wallust v3.3
#
# You can copy this file to ~/.config/wallust/wallust.toml (keep in mind is a sample config)

# SIMPLE TUTORIAL, or `man wallust.5`:
# https://explosion-mental.codeberg.page/wallust/
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml

# Global section - values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# backend = "fastresize" # full - resized - wal - thumb -  fastresize - kmeans
backend = "wal" # full - resized - wal - thumb -  fastresize - kmeans


# What color space to use to produce and select the most prominent colors:
color_space = "lch" # lab - labmixed - lch - lchmixed
# color_space = "ansidark" # lab - labmixed - lch - lchmixed

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16 #comp inverts the contrast colors to the initial one
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "harddark" #dark with colored background
# palette = "ansidark" #for ansi colorspace use with ansidark colorspace

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
check_contrast = true

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
saturation = 75

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ยก If either one is a directory, then both SHOULD be one. !
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }


#yazi.template = 'home/maike/.config/nixos/ressources/theming/wallust/templates/yazi-theme.toml'
#yazi.target = '/home/maike/.config/yazi/yazi-theme.toml'

ghostty.template = '/etc/nixos/resources/theming/wallust/templates/ghostty.theme'
ghostty.target = '/home/stary/.config/ghostty/colors-config'

#wezterm.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/wezterm.toml'
#wezterm.target = '/home/maike/.config/wezterm/colors-wezterm.toml'

hyprland.template = '/etc/nixos/resources/theming/wallust/templates/colors-hyprland.conf'
hyprland.target = '/home/stary/.config/hypr/colors-hyprland.conf'

#spicetify.template = '~/templates/colors-spicetify.ini'
#spicetify.target = '~/.config/spotify/Themes/wallust/color.ini'

#hyprpanel.template = "/etc/nixos/resources/theming/wallust/templates/hyprpanel.json"
# hyprpanel.target = "~/.config/config.hm.json"
#hyprpanel.target = "/home/stary/.config/hyprpanel/config.json"

waybar.template = '/etc/nixos/resources/theming/wallust/templates/waybar-colors.css' 
waybar.target = '/home/stary/.config/waybar/colors.css'

#neovim.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors-neovim.vim'
#neovim.target = '/home/maike/.config/nvim/colors/wallust.vim'

wofi.template = '/etc/nixos/resources/theming/wallust/templates/colors-wofi.css'
wofi.target = '/home/stary/.config/wofi/style.css'

#currently overwrites the whole tidal config
# tidal.template = '/home/maike/.config/nixos/ressources/wallust/templates/colors-tidalhifi.css'
# tidal.target = '/home/maike/.config/tidal-hifi/config.json'

rofi.template = '/etc/nixos/resources/theming/wallust/templates/rofi-colors.rasi'
rofi.target = '/home/stary/.config/rofi/colors.rasi'

#walker.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/walker-colors.css'
#walker.target = '/home/maike/.config/walker/themes/default.css'

#neopywal.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors_neopywal.vim'
# neopywal.target = '/home/maike/.cache/wallust/colors_neopywal.vim'
#neopywal.target = '/home/maike/.cache/wal/colors-wal.vim'

#foot.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors_foot.ini'
#foot.target = '~/.cache/wallust/colors_foot.ini'

#ags.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors_ags.css'
#ags.target = '~/.config/ags/colors_ags.css'

#cava.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors-cava'
#cava.target = '/home/maike/.config/cava/config'

#quickshell.template = '/etc/nixos/resources/theming/wallust/templates/colors-quickshell.qml'
#quickshell.target = '/home/stary/Downloads/github/quickshell/quickshell-examples/self/v1/Colors.qml'

#vesktop1.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors-vesktop-midnight.css'
#vesktop1.target = '/home/maike/.config/vesktop/themes/midnight-dynamic.theme.css'

#vesktop2.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors-vesktop-system24.css'
#vesktop2.target = '/home/maike/.config/vesktop/themes/system24-dynamic.theme.css'

#btop.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors-btop.tpl'
#btop.target = '~/.config/btop/themes/wallust.theme'

#zellij.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors-zellij.kdl'
#zellij.target = '~/.config/zellij/themes/wallust-theme.kdl'

#nix-active.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors-nix-active.nix'
#nix-active.target = '~/.config/nixos/ressources/theming/wallust/colors-nix-active.nix'

#noctalia.template = '/home/maike/.config/nixos/ressources/theming/wallust/templates/colors-noctalia.json'
#noctalia.target = '/home/maike/.config/noctalia/colors.json'
